spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    driver-class-name: org.postgresql.Driver
    username: ${USERS_DATASOURCE_USERNAME}
    password: ${USERS_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
rabbitmq:
  usuario:
    exchange: usuario.v1.exchange
    routingkey: usuario.cadastrado
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

default:
  admin:
    password: ${DEFAULT_ADMIN_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG